# Generated by Django 5.1 on 2024-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_userprofile_avatar_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
