# Generated by Django 5.1 on 2024-10-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_videos_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='completprogram',
            field=models.FileField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
