# Generated by Django 5.1 on 2024-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_videos_program_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='product_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
