# Generated by Django 5.1 on 2024-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=1),
        ),
    ]
